---
- name: Install Python3-PIP
  apt:
    name:
      - python3-pip
    update_cache: yes

- name: Create directory for HTTP server
  file:
    path: /home/ubuntu/basic-http-server
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Install Apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes